-- =================================
-- Test Queries for Performance Demo
-- =================================

CHECKPOINT;
DBCC DROPCLEANBUFFERS;
DBCC FREEPROCCACHE;

SET STATISTICS IO ON;
SET STATISTICS TIME ON;


-- 1 Total Orders per User
-- Aggregate query: Shows number of orders per user
SELECT 
    u.Id,
    u.FullName,
    COUNT(o.Id) AS TotalOrders
FROM [identity].Users u
JOIN sales.Orders o
    ON u.Id = o.UserId
GROUP BY u.Id, u.FullName
ORDER BY TotalOrders DESC


-- 2 Top 10 Best Selling Products
-- Aggregate + Join: Shows most sold products
SELECT TOP 10
    p.Id,
    p.Name,
    SUM(oi.Quantity) AS TotalSold
FROM sales.OrderItems oi
JOIN catalog.Products p
    ON oi.ProductId = p.Id
GROUP BY p.Id, p.Name
ORDER BY TotalSold DESC


-- 3 Total Revenue per User
-- Aggregate query: Total revenue generated by each user
SELECT 
    u.Id,
    u.FullName,
    SUM(o.TotalAmount) AS TotalRevenue
FROM [identity].Users u
JOIN sales.Orders o
    ON u.Id = o.UserId
GROUP BY u.Id, u.FullName
ORDER BY TotalRevenue DESC


-- 4 Order Details for a Specific User
-- Multi-join: Shows all products and quantities for a specific user's orders
SELECT 
    o.Id,
    p.Name,
    oi.Quantity
FROM sales.Orders o
JOIN sales.OrderItems oi
    ON o.Id = oi.OrderId
JOIN catalog.Products p
    ON oi.ProductId = p.Id
WHERE o.UserId = 11


-- 5 Latest Orders for a User
-- Filtering + Ordering: Returns most recent orders
SELECT *
FROM sales.Orders
WHERE UserId = 8
ORDER BY OrderDate DESC


-- 6 Products in a Category
-- Join + Filter: Shows all products for a category
SELECT 
    p.Name,
    c.Name AS CategoryName
FROM catalog.Products p
JOIN catalog.Categories c
    ON p.CategoryId = c.Id
WHERE p.CategoryId = 3

-- 7 Active Products
-- Filtered index scenario: Only active products
SELECT 
    p.Name,
    c.Name
FROM catalog.Products p
JOIN catalog.Categories c
    ON p.CategoryId = c.Id
WHERE p.IsActive = 1


-- 8 Orders by Status
-- Grouping + Aggregation: Shows total orders per status
SELECT 
    Status,
    COUNT(*) AS TotalOrders
FROM sales.Orders
GROUP BY Status
ORDER BY TotalOrders DESC


-- 9 Product Sales and Revenue
-- Multi-join + Aggregation: Total quantity sold and revenue per product
SELECT 
    p.Name,
    SUM(oi.Quantity) AS Sold,
    SUM(oi.Quantity * oi.Price) AS Revenue
FROM sales.OrderItems oi
JOIN catalog.Products p
    ON oi.ProductId = p.Id
GROUP BY p.Name
ORDER BY Revenue DESC


-- 10 Full Order History for a User
-- Multi-join + Ordering: Complete order details for a user
SELECT 
    u.FullName,
    o.Id AS OrderId,
    p.Name,
    oi.Quantity
FROM [identity].Users u
JOIN sales.Orders o
    ON u.Id = o.UserId
JOIN sales.OrderItems oi
    ON o.Id = oi.OrderId
JOIN catalog.Products p
    ON oi.ProductId = p.Id
WHERE u.Id = 2
ORDER BY o.OrderDate DESC
